name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Build package
        run: npm run build
      
      - name: Test package contents
        run: |
          echo "Testing package contents..."
          npm pack --dry-run
          
          # Verify dist folder exists and contains expected files
          if [ ! -d "dist" ]; then
            echo "❌ dist folder not found after build"
            exit 1
          fi
          
          if [ ! -f "dist/index.js" ]; then
            echo "❌ dist/index.js not found"
            exit 1
          fi
          
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ dist/index.d.ts not found"
            exit 1
          fi
          
          if [ ! -d "dist/templates" ]; then
            echo "❌ dist/templates folder not found"
            exit 1
          fi
          
          if [ ! -d "dist/assets" ]; then
            echo "❌ dist/assets folder not found"
            exit 1
          fi
          
          echo "✅ All required files found in dist folder"

  lint-formatting:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check code formatting
        run: npm run format -- --check
      
      - name: Run linting
        run: npm run lint 